
name: Sync

on: tepush:
    branches:
      - main
    paths:
     - 'requirements.txt'
     - 'runtime.txt'

name: Files
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.0.1
        with:
          GITHUB_TOKEN: '${{ secrets.SYNC_GITHUB_TOKEN }}'
          FILE_PATTERNS: |-
            ^requirements.txt
            ^runtime.txt
          TARGET_REPOS: |-
            ${{ github.actor }}/business_analysis_env
