name: fsync

on:
  push:
    branches:
      - main
    paths:
      - requirement.txt
      - runtime.txt

jobs:
  file_sync:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        - name: gh_fsync
          uses: gleich/gh_fsync@master
          with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}