name: fsync

on:
  push:
    branches:
      - main

jobs:
  gh_fsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SYNC_GITHUB_TOKEN }}
      - uses: gleich/gh_fsync@master