# Sync requirements.txt and runtime.txt to https://github.com/tan-yong-sheng/business_analytics_env
name: Sync Files to Another Repository

on: 
  push:
    paths:
     - 'requirements.txt'
     - 'runtime.txt'
    branches: ['main']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      - name: Push Changes
        run: |
          git remote add new_remote https://github.com/${{github.actor}}/business_analytics_env.git
          git add requirements.txt
          git add runtime.txt
          git commit -m "sync file"
          git push origin main
