name: Sync

on: 
  push:
    branches:
      - main
    paths:
     - 'requirements.txt'
     - 'runtime.txt'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      - name: Push Changes
        run: |
          git status
          git diff
          git config --local user.email "${{github.event.pusher.email}}"
          git config --local user.name "${{github.event.pusher.name}}"
          git remote set-url deploy https://${{secrets.SYNC_GITHUB_TOKEN}}@github.com/${{github.actor}}/business_analytics_env
          git add runtime.txt
          git add requirements.txt
          git commit -m "Sync files"
          git push main deploy
